const PATIENT_DOES_NOT_EXIST = 404
const DOCUMENT_DOES_NOT_EXIST = 404
const PATIENT_CREATION_FAILED = 500

module.exports = {
    PATIENT_DOES_NOT_EXIST,
    DOCUMENT_DOES_NOT_EXIST,
    PATIENT_CREATION_FAILED
}